# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f304d39384e7c715199a7d89573841689ddd5349172ad16cb40c73238efc8d090a95a79c410d889027f9fc09a60e285d850cd0d1d5414c7689a42996cb9e736e

test:
  secret_key_base: 649a93ecaf0da6b3c071bdd5a9423131286fdc307db429fc37faa26d0b99a39a782f001990c89b028c9e3d2a8d8b86d937595b8939aab2f9448fee10e4351631

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
